#!/bin/bash
#==============================================================================
#
#   DESCRIPTION:  test if tip-notes is uninstalled
# 
#         USAGE:  ./test-uninstalled
# 
#        AUTHOR:  S. Falcao
#       CREATED:  08.08.2020 18:25 BRST
# 
#==============================================================================

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     tip-notes is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     tip-notes is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <https://www.gnu.org/licenses/>



set -o errexit
#set -o nounset
set -o pipefail
#set -o xtrace

source ../tip-notes/project-header.sh


#---------
# HEADER
#---------
__script_name__="test-installed"


exit_status=0

# check binaries
if [[ -d "${__project_binaries_folder__}" ]]; then
    for element in ../tip-notes/*; do
        element="$(basename ${element})"
        if [[ ! -f "${__project_binaries_folder__}/${element}" ]]; then
            echo ".. ${__project_binaries_folder__}/${element} --> file is missing!"
            exit_status=1
        fi
    done
else
    echo "[${__project_binaries_folder__}] --> folder is missing!"
    exit_status=1
fi


# check docs
if [[ -d "${__project_doc_folder__}" ]]; then
    if [[ ! -f "${__project_doc_folder__}/copyright" ]]; then
        echo ".. ${__project_doc_folder__}/copyright} --> file is missing!"
        exit_status=1
    fi
else
    echo "[${__project_doc_folder__}] --> folder is missing!"
    exit_status=1
fi


# check autocompletion
if [[ ! -f "${__project_autocompletion_file__}" ]]; then
    echo ".. ${__project_autocompletion_file__} --> file is missing!"
    exit_status=1
fi

# check link
if [[ ! -f "${__project_links_folder__}/tip" ]]; then
    echo ".. ${__project_links_folder__}/tip --> link is missing/broken!"
    exit_status=1
fi

if [[ -d "${tip_config_folder}" ]]; then
    if [[ ! -f "${tip_config_file}" ]]; then
        echo ".. ${tip_config_file} --> file is missing!"
        exit_status=1
    fi
else
    echo "[${tip_config_folder}] --> folder is missing!"
    exit_status=1
fi


exit ${exit_status}
