#!/bin/bash
#==============================================================================
#
#   DESCRIPTION:  test if tip-notes is uninstalled
# 
#         USAGE:  ./test-uninstalled
# 
#        AUTHOR:  S. Falcao
#       CREATED:  08.08.2020 18:25 BRST
# 
#==============================================================================

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     tip-notes is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     tip-notes is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <https://www.gnu.org/licenses/>



set -o errexit
#set -o nounset
set -o pipefail
#set -o xtrace

source ../tip-notes/project-header.sh


#---------
# HEADER
#---------
__script_name__="test-installed"


exit_status=0

# check binaries
if [[ -d "${___HEADER___PROJECT_EXECUTABLES_FOLDER___}" ]]; then
    for element in ../tip-notes/*; do
        element="$(basename ${element})"
        if [[ ! -f \
        "${___HEADER___PROJECT_EXECUTABLES_FOLDER___}/${element}" ]]; then
            echo \
                "[${___HEADER___PROJECT_EXECUTABLES_FOLDER___}/${element}"
                "           "\
                "] --> file is missing!"
            exit_status=1
        fi
    done
else
    echo \
        "[${___HEADER___PROJECT_EXECUTABLES_FOLDER___}"\
        "             "\
        "] --> folder is missing!"
    exit_status=1
fi


# check docs
if [[ -d "${___HEADER___PROJECT_DOC_FOLDER___}" ]]; then
    if [[ ! -f "${___HEADER___PROJECT_DOC_FOLDER___}/copyright" ]]; then
        echo \
            "[${___HEADER___PROJECT_DOC_FOLDER___}/copyright}"\
            "              "\
            "--> file is missing!"
        exit_status=1
    fi
else
    echo "[${___HEADER___PROJECT_DOC_FOLDER___}"\
        "       "\
        "] --> folder is missing!"
    exit_status=1
fi


# check autocompletion
if [[ ! -f "${___HEADER___PROJECT_AUTOCOMPLETION_FILE___}" ]]; then
    echo \
        "[${___HEADER___PROJECT_AUTOCOMPLETION_FILE___}"\
        ""\
        "] --> file is missing!"
    exit_status=1
fi

# check link
if [[ ! -f "${___HEADER___PROJECT_LINKS_FOLDER___}/tip" ]]; then
    echo \
        "[${___HEADER___PROJECT_LINKS_FOLDER___}/tip"\
        "             "\
        "] --> link is missing/broken!"
    exit_status=1
fi

# check man page
if [[ ! -f "${___HEADER___PROJECT_MAN_FOLDER___}/tip.1.gz" ]]; then
    echo \
        "[${___HEADER___PROJECT_MAN_FOLDER___}/tip.1.gz"\
        "   "\
        "] --> man page is missing!"
    exit_status=1
fi


if [[ -d "${___HEADER___PROJECT_CONFIG_FOLDER___}" ]]; then
    if [[ ! -f "${___HEADER___PROJECT_CONFIG_FILE___}" ]]; then
        echo \
            "[${___HEADER___PROJECT_CONFIG_FILE___}"\
            "   "\
            "--> file is missing!"
        exit_status=1
    fi
else
    echo "[${___HEADER___PROJECT_CONFIG_FOLDER___}"\
        " "\
        "] --> folder is missing!"
    exit_status=1
fi


exit ${exit_status}
