#!/bin/bash
#==============================================================================
#
#   DESCRIPTION:  install tip notes
# 
#         USAGE:  ./install
# 
#        AUTHOR:  S. Falcao
#       CREATED:  11.07.2020 16:09
#
#==============================================================================


__SCRIPT_NAME__="install"

# get:
# __project_name__, __project_binaries_folder__, __project_links_folder__
#
# from project-header file
source ./tip-notes/project-header.sh


# if any command line parameter has been passed display help message
if [[ $# -gt 0 ]]; then
    echo "${__SCRIPT_NAME__}"
    echo "installs ${__project_name__}"
    echo
    echo "usage:"
    echo
    echo "  sudo ./${__SCRIPT_NAME__}"
    echo
    exit 1
fi

if ! mkdir -p "${__project_binaries_folder__}"; then
    echo "ERROR: destination folder could not be created"
    exit 1
fi

cp -r ./tip-notes/* "${__project_binaries_folder__}"
cp remove "${__project_binaries_folder__}"

# create links to executables
ln -s "${__project_binaries_folder__}/tip" "${__project_links_folder__}"
