#!/bin/bash
#=============================================================================
#
#   DESCRIPTION:  install tip notes
# 
#         USAGE:  ./install
# 
#        AUTHOR:  S. Falcao
#       CREATED:  11.07.2020 16:09
#
#=============================================================================


__SCRIPT_NAME__="install"

# get:
# __project_name__, __project_binaries_folder__, __project_links_folder__
#
# from project-header file
source ./tip-notes/project-header.sh

echo
echo "ATTENTION!"
echo
echo \
    "We strongly recommend to always install and remove "\
    "${___HEADER___PROJECT_NAME___}"
echo "trough assistance of system packaging manager. Please check README.md"
echo "installation section to see how to do it!"
echo
read -r -p "Ignore this warning and install? Type 'YES' to proceed: " answer
echo
if [[ "${answer}" != 'YES' ]]; then
    echo "Installation aborted by user!"
    echo
    exit 1
fi

# aborts if already installed by apt
if apt list --installed 2> /dev/null | grep 'tip-notes'; then
    echo
    echo "ATTENTION!"
    echo
    echo\
        "${___HEADER___PROJECT_NAME___} has already been installed "\
        "using apt system's package manager!"
    echo
    echo "Remove installed version using:"
    echo "sudo apt remove tip-notes"
    echo
    echo "then, call this script again"
    echo
    exit 1
fi


# if any command line parameter has been passed display help message
if [[ $# -gt 0 ]]; then
    echo "${__SCRIPT_NAME__}"
    echo "installs ${___HEADER___PROJECT_NAME___}"
    echo
    echo "usage:"
    echo
    echo "  sudo ./${__SCRIPT_NAME__}"
    echo
    exit 1
fi

if ! mkdir -p "${___HEADER___PROJECT_EXECUTABLES_FOLDER___}"; then
    echo "ERROR: destination folder could not be created"
    exit 1
fi

cp -r ./tip-notes/* "${___HEADER___PROJECT_EXECUTABLES_FOLDER___}"
#cp remove "${__project_binaries_folder__}"

if [[ -d /etc/bash_completion.d ]]; then
    cp \
        ./autocompletion/tip.bash \
        "${___HEADER___PROJECT_AUTOCOMPLETION_FOLDER___}"
fi

# create links to executables
ln -s \
    "${___HEADER___PROJECT_EXECUTABLES_FOLDER___}/tip" \
    "${___HEADER___PROJECT_LINKS_FOLDER___}"

# create docs
mkdir -p "${___HEADER___PROJECT_DOC_FOLDER___}"
cp ./packaging/copyright "${___HEADER___PROJECT_DOC_FOLDER___}"

# copy autocomplete file
cp ./autocompletion/tip.bash "${___HEADER___PROJECT_AUTOCOMPLETION_FILE___}"

# copy man page
cp ./man/tip.1 "${___HEADER___PROJECT_MAN_FOLDER___}/tip.1"
gzip "${___HEADER___PROJECT_MAN_FOLDER___}/tip.1"

# create config files if does not exist
"${___HEADER___PROJECT_EXECUTABLES_FOLDER___}/init" &> /dev/nul

