#!/bin/bash
#=============================================================================
#
#   DESCRIPTION:  install tip notes
# 
#         USAGE:  ./install
# 
#        AUTHOR:  S. Falcao
#       CREATED:  11.07.2020 16:09
#
#=============================================================================


script_name="$(basename ${0})"

# get:
# __project_name__, __project_binaries_folder__, __project_links_folder__
#
# from project-header file
source ./tip-notes/project-header.sh

echo
echo "ATTENTION!"
echo
echo \
    "We strongly recommend to always install and remove "\
    "${HEADER___PROJECT_NAME}"
echo "trough assistance of system packaging manager. Please check README.md"
echo "installation section to see how to do it!"
echo
read -r -p "Ignore this warning and install? Type 'YES' to proceed: " answer
echo
if [[ "${answer}" != 'YES' ]]; then
    echo "Installation aborted by user!"
    echo
    exit 1
fi

# aborts if already installed by apt
if apt list --installed 2> /dev/null | grep 'tip-notes'; then
    echo
    echo "ATTENTION!"
    echo
    echo\
        "${HEADER___PROJECT_NAME} has already been installed "\
        "using apt system's package manager!"
    echo
    echo "Remove installed version using:"
    echo "sudo apt remove tip-notes"
    echo
    echo "then, call this script again"
    echo
    exit 1
fi


# if any command line parameter has been passed display help message
if [[ $# -gt 0 ]]; then
    echo "${script_name}"
    echo "installs ${HEADER___PROJECT_NAME}"
    echo
    echo "usage:"
    echo
    echo "  sudo ./${script_name}"
    echo
    exit 1
fi

if ! mkdir -p "${HEADER___PROJECT_EXECUTABLES_FOLDER}"; then
    echo "ERROR: destination folder could not be created"
    exit 1
fi

cp -r ./tip-notes/* "${HEADER___PROJECT_EXECUTABLES_FOLDER}"
#cp remove "${__project_binaries_folder__}"

if [[ -d /etc/bash_completion.d ]]; then
    cp \
        ./autocompletion/tip.bash \
        "${HEADER___PROJECT_AUTOCOMPLETION_FOLDER}"
fi

# create links to executables
ln -s \
    "${HEADER___PROJECT_EXECUTABLES_FOLDER}/tip" \
    "${HEADER___PROJECT_LINKS_FOLDER}"

# create docs
mkdir -p "${HEADER___PROJECT_DOC_FOLDER}"
cp ./packaging/copyright "${HEADER___PROJECT_DOC_FOLDER}"

# copy autocomplete file
cp ./autocompletion/tip.bash "${HEADER___PROJECT_AUTOCOMPLETION_FILE}"

# copy man page
cp ./man/tip.1 "${HEADER___PROJECT_MAN_FOLDER}/tip.1"
gzip "${HEADER___PROJECT_MAN_FOLDER}/tip.1"

# create config files if does not exist
"${HEADER___PROJECT_EXECUTABLES_FOLDER}/init" &> /dev/nul

