#!/bin/bash
#==============================================================================
#
#   DESCRIPTION:  remove tip notes
#
#         USAGE:  ./remove
# 
#        AUTHOR:  S. Falcao
#       CREATED:  11.07.2020 16:09 BRST
#
#==============================================================================

__script_name__="remove"

# get:
# __project_name__, __project_binaries_folder__, __project_links_folder__
#
# from project-header file
source ./tip-notes/project-header.sh


# if parameters are passed shows help
if [[ $# -gt 0 ]]; then
    echo
    echo "remove ${__project_name__}"
    echo
    echo "usage:"
    echo
    echo "  sudo ${__script_name__}"
    echo
    exit 1
fi

# remove files and folders destination
rm -r "${__project_binaries_folder__}"

# remove links
rm "${__project_links_folder__}/tip"
