#!/usr/bin/env bash



# remove links
rm -f "___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_LINKS_FOLDER___/___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_EXECUTABLE_FILE_NAME_1___"

# remove config folder if required
if [[ "${1}" == "purge" ]]; then
    rm -rf "___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_CONFIG_FOLDER___"
fi
