#!/usr/bin/env bash


# create link
ln -s \
    "___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_EXECUTABLES_FOLDER___/___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_EXECUTABLE_FILE_NAME_1___" \
    "___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_LINKS_FOLDER___"

# create config files if not already existent
if [[ ! -f "___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_CONFIG_FILE___" ]]; then
    "___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_EXECUTABLES_FOLDER___/init-config.sh"
fi

exit 0
