#!/usr/bin/env bash

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>


# create package folder according to project name, version and architecture
package_name=''
package_name="${__project_name__}_${__project_version__}_${package_architecture}"
package_folder="${destination_folder}${package_name}"

if [[ -d "${package_folder}" ]]; then
    echo "ERROR: package folder already exist! Creation aborted!"
    exit 1
fi
mkdir -p "${package_folder}"
