#!/usr/bin/env bash

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>


#set -o errexit
#set -o nounset
#set -o pipefail
#set -o xtrace


#---------
# HEADER
#---------
script_name=$(basename "${0}")

package_architecture='all'


#---------------
# MAIN ROUTINE
#---------------

source ../tip-notes/project-header.sh
source ./make-deb-lib.sh
source ../tip-notes/tip-lib.sh


destination_folder="${1}"



if [[ "${#}" -eq 0 ]]; then
    print_error "ERROR: destination folder missing!"
    print_error
    print_error 'usage:'
    print_error "${script_name} <destination folder>"
    print_error
    exit 1
fi

if ! [[ -d "${destination_folder}" ]]; then
    print_error "ERROR: destination folder does not exist!"
    exit 1
fi


# 1. create package folder named according to conventions
source ./make-deb-create-pack-folder


# 2. add elements to package folder as required.
#    Uncomment optional elements to activate
source ./make-deb-control-files
source ./make-deb-exec
source ./make-deb-autocompletion
source ./make-deb-doc
source ./make-deb-man


# 3. build the deb file from package folder
cd "${destination_folder}"
dpkg-deb --build "${package_folder}"
