#!/usr/bin/env bash

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>



source ./make-deb-header 



# deal with DEBIAN files

# copy control files
cp -r ./DEBIAN "${PCKHEADER___PACKAGE_FOLDER}"

# adjust project name and version number in control file
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_NAME___|${HEADER___PROJECT_NAME}|" \
    "${PCKHEADER___PACKAGE_FOLDER}/DEBIAN/control"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_VERSION___|${HEADER___PROJECT_VERSION}|" \
    "${PCKHEADER___PACKAGE_FOLDER}/DEBIAN/control"



# edit and ajust permissions of postinst file
postinst_file="${PCKHEADER___PACKAGE_FOLDER}/DEBIAN/postinst"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_EXECUTABLES_FOLDER___|${HEADER___PROJECT_EXECUTABLES_FOLDER}|" \
    "${postinst_file}"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_EXECUTABLE_FILE_NAME_1___|${HEADER___PROJECT_EXECUTABLE_FILE_NAME_1}|" \
    "${postinst_file}"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_LINKS_FOLDER___|${HEADER___PROJECT_LINKS_FOLDER}|" \
    "${postinst_file}"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_CONFIG_FILE___|${HEADER___PROJECT_CONFIG_FILE}|" \
    "${postinst_file}"

chmod 755 "${postinst_file}"



# edit and ajust permissions of postrm file
postrm_file="${PCKHEADER___PACKAGE_FOLDER}/DEBIAN/postrm"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_EXECUTABLE_FILE_NAME_1___|${HEADER___PROJECT_EXECUTABLE_FILE_NAME_1}|" \
    "${postrm_file}"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_LINKS_FOLDER___|${HEADER___PROJECT_LINKS_FOLDER}|" \
    "${postrm_file}"
sed -i \
    "s|___WILL_BE_CHANGED_BY_MAKE_DEB___PROJECT_CONFIG_FOLDER___|${HEADER___PROJECT_CONFIG_FOLDER}|" \
    "${postrm_file}"
chmod 755 "${postrm_file}"
