#!/usr/bin/env bash

# Copyright (C) ___WILL_BE_CHANGED_BY_CONFIG___PROJECT_START_YEAR___ ___WILL_BE_CHANGED_BY_CONFIG___PROJECT_NAME___ authors.
#
# This file is part of ___WILL_BE_CHANGED_BY_CONFIG___PROJECT_NAME___
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>



# build the deb file from package folder
cd "${PCKHEADER___ARGUMENT_DESTINATION_FOLDER}"
dpkg-deb --build "${PCKHEADER___PACKAGE_FOLDER}"
