#!/usr/bin/env bash

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>



# deal with DEBIAN files

# copy control files
cp -r ./DEBIAN "${package_folder}"

# adjust project name and version number in control file
sed -i \
    "s|___CHANGE_HERE___PROJECT_NAME___|${___HEADER___PROJECT_NAME___}|" \
    "${package_folder}/DEBIAN/control"
sed -i \
    "s|___CHANGE_HERE___PROJECT_VERSION___|${___HEADER___PROJECT_VERSION___}|" \
    "${package_folder}/DEBIAN/control"

# ajust executables and links folders in postinst file
postinst_file="${package_folder}/DEBIAN/postinst"
sed -i \
    "s|___CHANGE_HERE___EXECUTABLES_FOLDER___|${___HEADER___PROJECT_EXECUTABLES_FOLDER___}|" \
    "${postinst_file}"
sed -i \
    "s|___CHANGE_HERE___LINKS_FOLDER___|${___HEADER___PROJECT_LINKS_FOLDER___}|" \
    "${postinst_file}"
sed -i \
    "s|___CHANGE_HERE___CONFIG_FILE___|${___HEADER___PROJECT_CONFIG_FILE___}|" \
    "${postinst_file}"
chmod 755 "${postinst_file}"


# ajust links and config folders in postrm file
postrm_file="${package_folder}/DEBIAN/postrm"
sed -i \
    "s|___CHANGE_HERE___LINKS_FOLDER___|${___HEADER___PROJECT_LINKS_FOLDER___}|" \
    "${postrm_file}"
sed -i \
    "s|___CHANGE_HERE___CONFIG_FOLDER___|${___HEADER___PROJECT_CONFIG_FOLDER___}|" \
    "${postrm_file}"
chmod 755 "${postrm_file}"
