#!/usr/bin/env bash
#===============================================================================
#
#   DESCRIPTION: edit tip-notes config file
# 
#         USAGE: ./config
#                
#        AUTHOR: S. Falcao
#       CREATED: 24.01.2021 15:43

#===============================================================================

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     tip-notes is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     tip-notes is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <https://www.gnu.org/licenses/>



#set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace


#-------------------------------------------------------------------------------
# CONFIGURATION SECTION
#-------------------------------------------------------------------------------
#
script_name=$(basename "${0}")

link_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
linked_script=$(readlink "${link_dir}/${script_name}")
if [[ -z "${linked_script}" ]]; then
    executables_dir="${link_dir}"
else
    executables_dir=$(dirname "${linked_script}")
fi
# shellcheck source=./project-header.sh
source "${executables_dir}/project-header.sh"
# shellcheck source=./tip-lib.sh
source "${executables_dir}/tip-lib.sh"

# if exist a config file, source it, otherwise prints an error
# message, unless $1 is --config-init
if [[ -f "${HEADER___PROJECT_CONFIG_FILE}" ]]; then
    # shellcheck source=/home/falcao/.config/tip-notes/tiprc
    source "${HEADER___PROJECT_CONFIG_FILE}"
else
    if [[ "${#}" -eq 0 ]] || [[ "${1}" != '--init' ]]; then
        print_error "ERROR: --> configuration file does not exist!"
        exit 1
    fi
fi



#-------------------------------------------------------------------------------
# MAIN SECTION
#-------------------------------------------------------------------------------
#

if [[ -s "${HEADER___PROJECT_CONFIG_FILE}" ]]; then
    if [[ -z "${RC___TIP_EDITOR}" ]]; then
        xdg-open "${HEADER___PROJECT_CONFIG_FILE}"
    else
        "${RC___TIP_EDITOR}" "${HEADER___PROJECT_CONFIG_FILE}"
    fi
    exit 0
fi

print_error "ERROR: config file not found!"
exit 1
