#!/usr/bin/env bash
#===============================================================================
#
#   DESCRIPTION: creates a brand new tip-notes config file
# 
#         USAGE: ./config-init
#                
#        AUTHOR: S. Falcao
#       CREATED: 11.07.2020 16:09

#===============================================================================

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     tip-notes is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     tip-notes is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <https://www.gnu.org/licenses/>



set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace


#-------------------------------------------------------------------------------
# CONFIGURATION SECTION
#-------------------------------------------------------------------------------
#
__script_name__="config-init"

source ./project-header.sh

# if doesn't exist a config folder create one
if ! [[ -d "${tip_config_folder}" ]]; then
    mkdir ${tip_config_folder}
fi

# if exist a config file, skip creation
if [[ -f "${tip_config_file}" ]]; then
    echo "ERROR: config file already exist!"
    exit 1
fi


#-------------------------------------------------------------------------------'
# MAIN SECTION'
#-------------------------------------------------------------------------------'

cp ./tiprc-default "${tip_config_file}"
