#!/usr/bin/env bash
#===============================================================================
#
#   DESCRIPTION: find notes by content
# 
#         USAGE: ./find-notes-by-content
#                
#        AUTHOR: S. Falcao
#       CREATED: 09.08.2020 17:26

#===============================================================================

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     tip-notes is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     tip-notes is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <https://www.gnu.org/licenses/>



#set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace


#-------------------------------------------------------------------------------
# CONFIGURATION SECTION
#-------------------------------------------------------------------------------
#
script_name=$(basename "${0}")

link_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
linked_script=$(readlink "${link_dir}/${script_name}")
if [[ -z "${linked_script}" ]]; then
    EXECUTABLES_DIR="${link_dir}"
else
    EXECUTABLES_DIR=$(dirname "${linked_script}")
fi
# shellcheck source=./project-header.sh
source "${EXECUTABLES_DIR}/project-header.sh"




if [[ -f "${HEADER___PROJECT_CONFIG_FILE}" ]]; then
# shellcheck source=/home/falcao/.config/tip-notes/tiprc
    source "${HEADER___PROJECT_CONFIG_FILE}"
else
    echo "ERROR: --> configuration file does not exist!"
    echo
    echo "To fix it type:"
    echo "tip --init"
    echo
    exit 1
fi

folder_to_list=''
if [[ "${#}" -eq 1 ]]; then
    folder_to_list="${___CONFIG___TIP_NOTES_FOLDER}"
    text="${1}"
elif [[ "${#}" -eq 2 ]]; then
    folder_to_list="${___CONFIG___TIP_NOTES_FOLDER}/${1}"
    text="${2}"
    if ! [[ -d "${folder_to_list}" ]]; then
        echo "ERROR: [${1}] seems no to be a valid GROUP of notes"
        exit 1
    fi
else
    echo "ERROR: unexpected number os parameters"
    exit 1
fi

find "${folder_to_list}"\
    -type f\
    -print0\
    | xargs -0 grep -li "${text}"\
    | grep -oP "${folder_to_list}/\K.*"\
    | sort\
    | uniq
