#!/usr/bin/env bash
#===============================================================================
#
#   DESCRIPTION: creates a brand new tip-notes config file
# 
#         USAGE: ./init
#                
#        AUTHOR: S. Falcao
#       CREATED: 11.07.2020 16:09

#===============================================================================

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     tip-notes is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     tip-notes is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <https://www.gnu.org/licenses/>



#set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace


#-------------------------------------------------------------------------------
# CONFIGURATION SECTION
#-------------------------------------------------------------------------------
#
SCRIPT_NAME=$(basename "${0}")

LINK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINKED_SCRIPT=$(readlink "${LINK_DIR}/${SCRIPT_NAME}")
if [[ -z "${LINKED_SCRIPT}" ]]; then
    EXECUTABLES_DIR="${LINK_DIR}"
else
    EXECUTABLES_DIR=$(dirname "${LINKED_SCRIPT}")
fi
# shellcheck source=./project-header.sh
source "${EXECUTABLES_DIR}/project-header.sh"




# if doesn't exist a config folder create one
if ! [[ -d "${HEADER___PROJECT_CONFIG_FOLDER}" ]]; then
    mkdir "${HEADER___PROJECT_CONFIG_FOLDER}"
fi

# if exist a config file, skip creation
if [[ -f "${HEADER___PROJECT_CONFIG_FILE}" ]]; then
    echo "ERROR: config file already exist!"
    exit 1
fi


#-------------------------------------------------------------------------------'
# MAIN SECTION'
#-------------------------------------------------------------------------------'


if \
 ! cp \
    "${EXECUTABLES_DIR}/tiprc-default" \
    "${HEADER___PROJECT_CONFIG_FILE}"; then
    exit 1
fi

printf "Please, close terminal and open it again to changes take efect!\n"
