#!/usr/bin/env bash
#===============================================================================
#
#   DESCRIPTION: print a default config file
# 
#         USAGE: ./config-init
#                
#        AUTHOR: S. Falcao
#       CREATED: 11.07.2020 16:09

#===============================================================================

set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace


#-------------------------------------------------------------------------------
# CONFIGURATION SECTION
#-------------------------------------------------------------------------------
#
__script_name__="print-config"



#-------------------------------------------------------------------------------'
# MAIN SECTION'
#-------------------------------------------------------------------------------'

echo '#========================================================='
echo '# tip notes configuration file'
echo '#'
echo '# you are welcome to make changes in configurations'
echo '# bellow if you now what you are doing'
echo '#========================================================='
echo
echo
echo '#----------------------------------------------------------'
echo '# point to folder where notes are stored'
echo '#----------------------------------------------------------'
echo 'tip_notes_folder=~/.config/tip-notes/notes'
echo
echo '#----------------------------------------------------------'
echo '# choose alternative tip editor'
echo '# if no tip_editor is set then tip will use'
echo "# system's defaults to open the note"
echo '#'
echo '# eg:'
echo "# tip_editor='vim'"
echo "# tip_editor='nano'"
echo '#----------------------------------------------------------'
echo "#tip_editor='vim'"
echo
echo '#----------------------------------------------------------'
echo '# control if --remove will ask for confirmation or not'
echo '# IS SAFER TO KEEP IT true'
echo '#'
echo '# tip_confirm_remove=true       asks for confirmation'
echo '# tip_confirm_remove=false      removes without asking'
echo '#----------------------------------------------------------'
echo 'tip_confirm_remove=true'
echo
echo '#----------------------------------------------------------'
echo '# control if --remove-purge will ask for confirmation'
echo '# IS STRONGLY RECOMMENDED TO KEEP IT true'
echo '# Changing this option may lead to accidentally loosing all'
echo '# your notes'
echo '#'
echo '# tip_confirm_remove_purge=true     asks for confirmation'
echo '# tip_confirm_remove_purge=false    removes without asking'
echo '#----------------------------------------------------------'
echo 'tip_confirm_remove_purge=true'
echo
echo '#----------------------------------------------------------'
echo '# control if --config-reset will ask for confirmation'
echo '# IS SAFER TO KEEP IT true'
echo '#'
echo '# tip_confirm_config_reset          asks for confirmation'
echo '# tip_confirm_config_reset          resets without asking'
echo '#----------------------------------------------------------'
echo 'tip_confirm_config_reset=true'
