#!/bin/bash
#==============================================================================
#
#   DESCRIPTION:  remove tip-notes
#
#         USAGE:  ./remove
# 
#        AUTHOR:  S. Falcao
#       CREATED:  11.07.2020 16:09 BRST
#
#==============================================================================

SCRIPT_NAME=$(basename "${0}")

LINK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINKED_SCRIPT=$(readlink "${LINK_DIR}/${SCRIPT_NAME}")
if [[ -z "${LINKED_SCRIPT}" ]]; then
    EXECUTABLES_DIR="${LINK_DIR}"
else
    EXECUTABLES_DIR=$(dirname "${LINKED_SCRIPT}")
fi
# shellcheck source=./project-header.sh
source "${EXECUTABLES_DIR}/project-header.sh"



# if parameters are passed shows help
if [[ "${#}" -gt 0 ]] && [[ "${1}" != "--purge" ]]; then
    echo
    echo "usage:"
    echo
    echo "  sudo ${SCRIPT_NAME} [--purge]"
    echo
    exit 1
fi


# aborts if already installed by apt
if apt list --installed 2> /dev/null | grep 'tip-notes'; then
    echo
    echo "ATTENTION!"
    echo
    echo\
        "${___HEADER___PROJECT_NAME___} has been installed using apt system's"\
        "package manager!"
    echo
    if [[ "${1}" == "--purge" ]]; then
        echo "Purge installed version using:"
        echo "sudo apt purge tip-notes"
    else
        echo "Remove installed version using:"
        echo "sudo apt remove tip-notes"
    fi
    echo
    exit 1
fi

# remove files and folders destination
rm -r "${___HEADER___PROJECT_EXECUTABLES_FOLDER___}"

# remove autocompletion file
# TODO: expand to remove also fish autocompletion
rm "${___HEADER___PROJECT_AUTOCOMPLETION_FILE___}"

# remove links
rm "${___HEADER___PROJECT_LINKS_FOLDER___}/tip"

# remove docs
rm -r "${___HEADER___PROJECT_DOC_FOLDER___}"

# remove man page
rm -r /usr/local/man/man1/tip.1.gz

# purge files if required
if [[ "${1}" == "--purge" ]]; then
    rm -r "${___HEADER___PROJECT_CONFIG_FOLDER___}"
fi

exit 0
