#!/bin/bash
#==============================================================================
#
#   DESCRIPTION:  remove tip notes
#
#         USAGE:  ./remove
# 
#        AUTHOR:  S. Falcao
#       CREATED:  11.07.2020 16:09 BRST
#
#==============================================================================

__script_name__="remove"

# get:
# __project_name__, __project_binaries_folder__, __project_links_folder__
#
# from project-header file
source ./project-header.sh


# if parameters are passed shows help
if [[ "${#}" -gt 0 ]] && [[ "${1}" != "--purge" ]]; then
    echo
    echo "usage:"
    echo
    echo "  sudo ${__script_name__} [--purge]"
    echo
    exit 1
fi


# aborts if already installed by apt
if apt list --installed 2> /dev/null | grep 'tip-notes'; then
    echo
    echo "ATTENTION!"
    echo
    echo\
        "${__project_name__} has been installed using apt system's"\
        "package manager!"
    echo
    echo "Remove installed version using:"
    echo "sudo apt remove tip-notes"
    echo
    exit 1
fi

# remove files and folders destination
rm -r "${__project_binaries_folder__}"

# remove autocompletion file
rm "${__project_autocompletion_file__}"

# remove links
rm "${__project_links_folder__}/tip"

# remove docs
rm -r "${__project_doc_folder__}"

# puge files if required
if [[ "${1}" == "--purge" ]]; then
    rm -r "${tip_config_folder}"
fi

exit 0
