#!/usr/bin/env bash
#===============================================================================
#
#   DESCRIPTION: terminal notes manager
# 
#         USAGE: ./tip --help
#                
#        AUTHOR: S. Falcao
#       CREATED: 11.07.2020 16:09

#===============================================================================

# Copyright (C) 2020 tip-notes authors.
#
# This file is part of tip-notes.
#
#     tip-notes is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     tip-notes is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <https://www.gnu.org/licenses/>



#set -o errexit
set -o nounset
set -o pipefail
#set -o xtrace


#-------------------------------------------------------------------------------
# CONFIGURATION SECTION
#-------------------------------------------------------------------------------
#
SCRIPT_NAME=$(basename "${0}")

LINK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINKED_SCRIPT=$(readlink "${LINK_DIR}/${SCRIPT_NAME}")
if [[ -z "${LINKED_SCRIPT}" ]]; then
    EXECUTABLES_DIR="${LINK_DIR}"
else
    EXECUTABLES_DIR=$(dirname "${LINKED_SCRIPT}")
fi
# shellcheck source=./project-header.sh
source "${EXECUTABLES_DIR}/project-header.sh"

#echo $SCRIPT_NAME
#echo $EXECUTABLES_DIR

# if exist a config file, source it, otherwise prints an error
# message, unless $1 is --config-init
if [[ -f "${HEADER___PROJECT_CONFIG_FILE}" ]]; then
    # shellcheck source=/home/falcao/.config/tip-notes/tiprc
    source "${HEADER___PROJECT_CONFIG_FILE}"
else
    if [[ "${#}" -eq 0 ]] || [[ "${1}" != '--init' ]]; then
        echo
        echo "ERROR: --> configuration file does not exist!"
        echo
        echo "To fix it type:"
        echo "tip --init"
        echo
        exit 1
    fi
fi


#-------------------------------------------------------------------------------
# FUNCTIONS
#-------------------------------------------------------------------------------
# use this section to store your functions
#
#

#####
# P #
#####
#

function print_if_not_silenced(){
    if [[ "$FLAG_SILENT" -eq "0" ]] ; then
        echo "$1"
        return "0"
    else
        return "1"
    fi
}


function print_if_verbose(){
    if [[ "$FLAG_VERBOSE" -eq "1" ]] ; then
        echo "$1"
        return 0
    else
        return 1
    fi
}



#-------------------------------------------------------------------------------
# PARSING
#-------------------------------------------------------------------------------
#
POSITIONAL_ARGUMENTS=()


#VERBOSE_FLAG=0
#SILENT_FLAG=0


while [[ ${#} -gt 0 ]]; do

    arg="$1"

    case ${arg} in
        '-h' | '--help')
            shift # past argument
            echo
            echo \
                "${___HEADER___PROJECT_NAME___} "\
                "${___HEADER___PROJECT_VERSION___}"
            echo
            echo
            echo "USAGE:"
            echo
            echo \
                "${SCRIPT_NAME}                                    "\
                "list all notes"
            echo \
                "${SCRIPT_NAME} [<group>]                          "\
                "list all notes within the group"
            echo \
                "${SCRIPT_NAME} [<group>/]<note>                   "\
                "list specific note"
            echo
            echo \
                "${SCRIPT_NAME} --config                           "\
                "edit external configuration file"
            echo \
                "${SCRIPT_NAME} --init                             "\
                "create an external configuration file"
            echo \
                "${SCRIPT_NAME} --reset                            "\
                "reset external configuration file"
            echo
            echo \
                "${SCRIPT_NAME} --backup                           "\
                "creates a backup according to tiprc configuration"
            echo \
                "${SCRIPT_NAME} --backup --all                     "\
                "creates a backup containing notes and configurations"
            echo \
                "${SCRIPT_NAME} --backup --config-only             "\
                "creates a backup containing configurations"
            echo \
                "${SCRIPT_NAME} --backup --notes-only              "\
                "creates a backup containing notes"
            echo
            echo \
                "${SCRIPT_NAME} --edit [<group>/]<note>            "\
                "add/edit note"
            echo \
                "${SCRIPT_NAME} --delete [<group>/]<note>          "\
                "delete note"
            echo \
                "${SCRIPT_NAME} --find [<group>] <text>            "\
                "find notes which name contains <text>"
            echo \
                "${SCRIPT_NAME} --find-content [<group>] <text>    "\
                "find notes which contains <text>"
            echo
            echo \
                "${SCRIPT_NAME} --remove                           "\
                "remove ${___HEADER___PROJECT_NAME___} from system"
            echo \
                "${SCRIPT_NAME} --purge                            "\
                "remove ${___HEADER___PROJECT_NAME___} from system including"
            echo "                                       "\
                "configuration files and notes"
            echo
            echo \
                "${SCRIPT_NAME} --version                          "\
                "shows ${___HEADER___PROJECT_NAME___} version"
            echo \
                "${SCRIPT_NAME} --authors                          "\
                "shows ${___HEADER___PROJECT_NAME___} authors list"
            echo
            echo
            echo "SHORT FORMS:"
            echo
            echo "-b is same of --backup"
            echo "-d is same of --delete"
            echo "-e is same of --edit"
            echo "-f is same of --find"
            echo "-F is same of --find-content"
            echo "-h is same of --help"
            echo
            echo
            echo \
                "${SCRIPT_NAME} --help                             "\
                "shows ${___HEADER___PROJECT_NAME___}'s help"
            echo
            exit 0
            ;;
#        '-s' | '--silent')
#            SILENT_FLAG=1
#            shift # past argument
#            ;;
#        '-v' | '--verbose')
#            VERBOSE_FLAG=1
#            shift # past argument
#            ;;
        '-b' | '--backup')
            shift
            if [[ "${#}" -gt 0 ]]; then
                "${EXECUTABLES_DIR}/backup" "${@}"
            else
                "${EXECUTABLES_DIR}/backup"
            fi
            exit 0
            ;;
        '-e' | '--edit')
            shift
            if [[ ${#} -ne 1 ]]; then
                echo "ERROR: --edit option waits for a note name"
                exit 1
            fi
            note_file="${___CONFIG___TIP_NOTES_FOLDER}/${1}"

            if [[ -n "${note_file}" ]]; then
                mkdir -p "$(dirname "${note_file}")" && touch "${note_file}"
            fi
            if [[ -z "${___CONFIG___TIP_EDITOR}" ]]; then
                if ! [[ -f "${note_file}" ]]; then
                    touch "${note_file}"
                fi
                xdg-open "${note_file}"
            else
                "${___CONFIG___TIP_EDITOR}" "${note_file}"
            fi
            # removes a zero leght file that eventually remains
            if ! [[ -s ${note_file} ]]; then
                rm "${note_file}"
            fi
            exit 0
            ;;
        '-d' | '--delete')
            shift
            if [[ ${#} -ne 1 ]]; then
                echo "ERROR: --delete option waits for a note name"
                exit 1
            fi
            note_file="${___CONFIG___TIP_NOTES_FOLDER}/${1}"
            if [[ -f "${note_file}" ]]; then
                if [ "${___CONFIG___TIP_CONFIRM_DELETE_NOTE}" = true ]; then

                    read -r -p "Are you sure? (y/n): " answer
                    if ! [[ "${answer}" =~ [y|Y] ]]; then
                        echo "reset operation aborted by user!"
                        exit 1
                    fi

                fi
                rm "${note_file}"
            else
                echo "no ${1} note to be removed!"
                exit 1
            fi
            find "${___CONFIG___TIP_NOTES_FOLDER}" -type d -empty -delete
            exit 0
            ;;
        '-F' | '--find-content')
            shift
            if [[ "${#}" -eq 1 ]]; then
                "${EXECUTABLES_DIR}/find-notes-by-content" "${1}"
                exit 0
            elif [[ "${#}" -eq 2 ]]; then
                "${EXECUTABLES_DIR}/find-notes-by-content" "${1}" "${2}"
                exit 0
            fi
            echo "ERROR: --find-content received unexpected number of arguments!"
            echo
            echo "usage:"
            echo "${SCRIPT_NAME} --find-content [<group>] <text>"
            echo
            echo "[<group>] is optional"
            echo
            exit 1
            ;;
        '-f' | '--find')
            shift
            if [[ "${#}" -eq 1 ]]; then
                "${EXECUTABLES_DIR}/find-notes-by-name" "${1}"
                exit 0
            elif [[ "${#}" -eq 2 ]]; then
                "${EXECUTABLES_DIR}/find-notes-by-name" "${1}" "${2}"
                exit 0
            fi
            echo "ERROR: --find received unexpected number of arguments!"
            echo
            echo "usage:"
            echo "${SCRIPT_NAME} --find [<group>] <text>"
            echo
            echo "[<group>] is optional"
            echo
            exit 1
            ;;
        '--authors')
            cat "${EXECUTABLES_DIR}/authors"
            exit 0
            ;;
        '--config')
            if [[ -s "${HEADER___PROJECT_CONFIG_FILE}" ]]; then
                if [[ -z "${___CONFIG___TIP_EDITOR}" ]]; then
                    xdg-open "${HEADER___PROJECT_CONFIG_FILE}"
                else
                    "${___CONFIG___TIP_EDITOR}" "${HEADER___PROJECT_CONFIG_FILE}"
                fi
                exit 0
            fi
            echo "ERROR: config file not found! To create a config file type:"
            echo "tip --config-init"
            echo
            exit 1
            ;;
        '--init')
            "${EXECUTABLES_DIR}/init"
            exit 0
            ;;
        '--reset')
            if [ "${___CONFIG___TIP_CONFIRM_RESET}" = true ]; then
                read -r -p "Are you sure? (y/n): " answer
                if ! [[ "${answer}" =~ [y|Y] ]]; then
                    echo "reset operation aborted by user!"
                    exit 1
                fi
            fi
            rm "${HEADER___PROJECT_CONFIG_FILE}"
            "${EXECUTABLES_DIR}/init"
            exit 0
            ;;
        '--remove')
            if [ "${___CONFIG___TIP_CONFIRM_REMOVE}" = true ]; then
                read -r -p "Are you sure? (y/n): " answer
                if ! [[ "${answer}" =~ [y|Y] ]]; then
                    echo "remove operation aborted by user!"
                    exit 1
                fi
            fi
            "${EXECUTABLES_DIR}/remove"
            exit 0
            ;;
        '--purge')
            if [ "${___CONFIG___TIP_CONFIRM_PURGE}" = true ]; then
                read -r -p "Are you sure? (y/n): " answer
                if ! [[ "${answer}" =~ [y|Y] ]]; then
                    echo "purge operation aborted by user!"
                    exit 1
                fi
            fi
            "${EXECUTABLES_DIR}/remove" '--purge'
            exit 0
            ;;
        '--version')
            echo "${___HEADER___PROJECT_VERSION___}"
            exit 0
            ;;

        *)
            # unknown option
            # save it in an array for later
            POSITIONAL_ARGUMENTS+=("$1")
            shift # past argument
            ;;
    esac
done



# positional parameters are restored AUTOMATICALLY in order to be treated by the
# caller (DO NOT CHANGE BELLOW)
set -- "${POSITIONAL_ARGUMENTS[@]}"




#-------------------------------------------------------------------------------
# MAIN SECTION
#-------------------------------------------------------------------------------
#

# if no notes folfer creates one
if ! [[ -d "${___CONFIG___TIP_NOTES_FOLDER}" ]]; then
    mkdir "${___CONFIG___TIP_NOTES_FOLDER}"
fi

# if no arguments list available notes
if [[ "${#}" -eq 0 ]]; then
    # echo 'calling list-notes'
    "${EXECUTABLES_DIR}/list-notes"
    exit 0
fi

if [[ "${#}" -eq 1 ]]; then
    if [[ -d "${___CONFIG___TIP_NOTES_FOLDER}/${1}" ]]; then
        "${EXECUTABLES_DIR}/list-notes" "${1}"
        exit 0
    elif [[ -f "${___CONFIG___TIP_NOTES_FOLDER}/${1}" ]]; then
        more "${___CONFIG___TIP_NOTES_FOLDER}/${1}"
        exit 0
    fi

    echo "no tips for ${1}"
    exit 1
fi

echo "ERROR: Unexpected arguments!"
exit 1
